config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Setting the 'Home page' route use /root 
  root 'posts#index', as: 'home'

  # Default way to create a route
  get 'about' => 'pages#about', as: 'about'
  get '/signup',  to: 'users#new'
  # resources gives us create/new/show/update/destroy 
  # without having to create them ourselves
  resources :posts do 
  	resources :comments
  end

  resources :users#, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # rails g model comment username:string body:text post:references
  # This adds the below line belongs_to. 
  # We want this relationship with post since comments are
  # attached to it. 
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	validates :title, presence: true,
		length: { minimum: 5}
	validates :body, presence: true,
		length: { minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	validates :username, presence: true,
		length: { minimum: 7, maximum: 20}
	validates :email, presence: true
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "lolpresto", password: "1234", only: [:destroy]

	def create
		@post = Post.find(params[:post_id])

		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us';
		@content = 'This is the about page';
	end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with name: "lolpresto", password: "1234", except: [:index, :show]

	def index
		 @posts = Post.all 
	end 

	def new 
		@post = Post.new
	end 

	def show
		@post = Post.find(params[:id])	
	end 

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def create
		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def signup
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all 
	end

	def create
		@user = User.new(user_params)
		@users = User.new
		
		if(@user.save)
			redirect_to @users
		else
			render 'new'
		end
	end

	def new
		@user = User.new
	end

	private def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
	<div class='well' >
		<p><strong>
			<%= comment.username %>:
			<%= comment.body %>
		</strong>
		<%= link_to '[X]', [comment.post, comment],
				method: :delete,
				data: { confirm: 'Are you sure?' } %>
		</p>
	</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<div class='well' >
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :username %><br>
		<%= f.text_field(:username, {:class => 'form-control new-input'}) %>
	</p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, { :class => 'form-control new-input resizeArea', rows: 5}) %>
	<br>
	<p>
		<%= f.submit({:class => 'btn btn-default'}) %>
	</p>
<% end %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "simple" %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand">Blog</a> -->
          <%= link_to "Blog", home_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create Post", new_post_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", new_user_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  <div class='container'>
    <%= yield %>
	</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class='alert alert-danger'><%= msg %></div>
			<% end %>
		<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field(:title, {:class => 'form-control new-input'}) %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, {:class => 'form-control new-input', rows: 5}) %>
	</p>
	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %> 

app/views/posts/index.html.erb
<h1>Timeline</h1>
<% @posts.each do |post| %>
	<div class='well' >	
		<h3><%= post.title %></h3>
		<p><%= post.body %></p>
		<%= link_to 'Read more..', post_path(post), :class => 'btn btn-default' %>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>Add a Post</h1>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class='alert alert-danger'><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field(:title, {:class => 'form-control new-input'}) %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, {:class => 'form-control new-input input-lg resizeArea', rows: 5}) %>
	</p>
	<br>
	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<div class='well well-lg' >
<h3><%= @post.title %></h3>
<p><%= @post.body %></p>
</div>
<%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-default' %> 
<%= link_to 'Delete', post_path(@post), 
	method: :delete,
	data: {confirm: 'Are you sure?'},
	:class => 'btn btn-danger' %> 
<hr>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>

app/views/users/index.html.erb
<h3>List of current users</h3>
<% @users.each do |user| %>
	<div class='well'>	
		<h3><%= user.username %></h3>
		<p><%= user.email %></p>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Let's get started</h1>
<%= form_for :user, url: users_path do |f| %>
<div class='well '>
	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |msg| %>
			<div class='alert alert-danger'><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		<%= f.label :username %><br>
		<%= f.text_field(:username, {:class => 'form-control new-input '}) %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field(:email, {:class => 'form-control new-input '}) %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field(:password, {:class => 'form-control new-input '}) %>
	</p>
	<br>
	<p>
		<%= f.submit('Sign up', {:class => 'btn btn-primary'}) %>
	</p>
</div>
<% end %>

app/views/users/show.html.erb
<h3>List of current users</h3>
<%= @user.username %>, <%= @user.email %>

app/views/users/signup.html.erb
<h1>Let's get started</h1>
<%= form_for :user, url: users_path do |f| %>
	<p>
		<%= f.label :username %><br>
		<%= f.text_field(:username, {:class => 'form-control new-input'}) %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field(:email, {:class => 'form-control new-input input-lg'}) %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.text_field(:password_digest, {:class => 'form-control new-input input-lg'}) %>
	</p>
	<br>
	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>